LOGGER_NAME = 'main logger'

SUPPORTED_IMG_EXTENSIONS = {'.jpg', 'jpeg', '.png'}

SUPPORTED_FILE_EXTENSIONS = {'.pdf'}

SUPPORTED_EXTENSIONS = SUPPORTED_FILE_EXTENSIONS.union(SUPPORTED_IMG_EXTENSIONS)
